### PR TITLE
Add fetch historical rates for any day since 1999.

### PR DESCRIPTION
**Pull request by andrey-mostovoy**

### CODE REVIEW

**Comment by benmajor** [comment]
What is the benefit for this over something like: `$rates  = $lookup->addDateFrom('2015-01-20')->fetch();`?

Also, why the requirement for PHP 7.0?

**Comment by andrey-mostovoy** [comment]
requirement php 7.0 for scalar type hints are already presents in code.
Also `$rates = $lookup->addDateFrom('2015-01-20')->fetch();` didn't work right now. It's required `addToDate`, and it's  supposed to use a range of dates, not single day

**Comment by benmajor** [comment]
Okay, that makes sense. Thanks for the contribution - I have merged the request.

**Comment by andrey-mostovoy** [comment]
Ok, and thanks for the nice wrapper )

**Pull request merged**
